### ISSUE TITLE
Separate test failures from lint failures in CI config

### ISSUE THREAD

**Issue by ianb** [mozilla-services/screenshots#5024]
It would be nice to see test failures separate from lint failures in PRs. I think if we separate out things in `.circleci/config.yml` then it would work. Maybe like:

```
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - lint
      - test:
          requires:
            - lint
            - build
```

Then in the `jobs:` section we'd have to create a lint job.
